apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-1
spec:
  replicas: 1
  selector:
    component: kafka
    id: kafka-1 
  template:
    metadata:
      labels:
        component: kafka
        id: kafka-1
    spec:
      nodeSelector:
        infra-service: "false"
      containers:
      - name: kafka-1 
        image: 172.22.111.199:80/cloud/kafka-kubernetes:1.2
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ID 
          value: "1"
        - name: ZOOKEEPER_CONNECTION_STRING
          value: "zk:2181"
        ports:
        - containerPort: 9092
          name: port1
          protocol: TCP
        - containerPort: 7203
          name: port2
          protocol: TCP
        volumeMounts:
        - mountPath: "/data"
          name: data
      volumes:
          - name: "data"
            rbd:
              monitors:
              - "10.17.17.9:6789"
              - "10.17.17.10:6789"
              - "10.17.17.11:6789"
              pool: "rbd"
              image: "kafka-1"
              user: "admin"
              secretRef:
                name: "ceph-secret"
              keyring: "/etc/ceph/ceph.client.admin.keyring"
              fsType: "ext4"
              readOnly: false
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-2
spec:
  replicas: 1
  selector:
    component: kafka
    id: kafka-2
  template:
    metadata:
      labels:
        component: kafka
        id: kafka-2
    spec:
      nodeSelector:
        infra-service: "false"
      containers:
      - name: kafka-2
        image: 172.22.111.199:80/cloud/kafka-kubernetes:1.2
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: ZOOKEEPER_CONNECTION_STRING
          value: "zk:2181"
        ports:
        - containerPort: 9092
          name: port1
          protocol: TCP
        - containerPort: 7203
          name: port2
          protocol: TCP
        volumeMounts:
        - mountPath: "/data"
          name: data
      volumes:
          - name: "data"
            rbd:
              monitors:
              - "10.17.17.9:6789"
              - "10.17.17.10:6789"
              - "10.17.17.11:6789"
              pool: "rbd"
              image: "kafka-2"
              user: "admin"
              secretRef:
                name: "ceph-secret"
              keyring: "/etc/ceph/ceph.client.admin.keyring"
              fsType: "ext4"
              readOnly: false
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-3
spec:
  replicas: 1
  selector:
    component: kafka
    id: kafka-3
  template:
    metadata:
      labels:
        component: kafka
        id: kafka-3
    spec:
      nodeSelector:
        infra-service: "false"
      containers:
      - name: kafka-3
        image: 172.22.111.199:80/cloud/kafka-kubernetes:1.2
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: ZOOKEEPER_CONNECTION_STRING
          value: "zk:2181"
        ports:
        - containerPort: 9092
          name: port1
          protocol: TCP
        - containerPort: 7203
          name: port2
          protocol: TCP
        volumeMounts:
        - mountPath: "/data"
          name: data
      volumes:
          - name: "data"
            rbd:
              monitors:
              - "10.17.17.9:6789"
              - "10.17.17.10:6789"
              - "10.17.17.11:6789"
              pool: "rbd"
              image: "kafka-3"
              user: "admin"
              secretRef:
                name: "ceph-secret"
              keyring: "/etc/ceph/ceph.client.admin.keyring"
              fsType: "ext4"
              readOnly: false
