apiVersion: v1
kind: Service
metadata:
  name: kafka-monitor 
  namespace: default
  labels:
    component: kafka-monitor 
spec:
  selector:
    component: kafka-monitor
  type: NodePort
  ports:
  - name: port0
    port: 8080 
    nodePort: 30002
    protocol: TCP
